ways of creating array in numpy

In [1]:
from numpy import *

In [4]:
arr = array([1,2,3,4,5])
print(arr.dtype)

int32


In [5]:
arr = array([1,2,3,4.5,5])
print(arr.dtype)

float64


In [6]:
arr = array([1,2,3,4/5,5])
print(arr.dtype)

float64


In [7]:
arr = array([1,2%3,3,4,5])
print(arr.dtype)

int32


In [8]:
arr = array([1,2,3.6,4,5])
print(arr.dtype)
print(arr)

float64
[1.  2.  3.6 4.  5. ]


In [9]:
arr = array([1,2,3,4,5],float)
print(arr.dtype)

float64


In [10]:
arr = array([1,2,3,4,5],int)
print(arr.dtype)

int32


In [16]:
arr = linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [17]:
arr = linspace(0,10,15)
print(arr)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [18]:
arr = linspace(0,1,2)
print(arr)

[0. 1.]


In [31]:
arr = linspace(1,2,2)
print(arr)

[1. 2.]


In [35]:
arr = linspace(0,2,4)
print(arr)

[0.         0.66666667 1.33333333 2.        ]


In [37]:
arr = linspace(0,15,5)
print(arr)

[ 0.    3.75  7.5  11.25 15.  ]


In [39]:
arr = linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [41]:
arr = linspace(0,16,20)
print(arr)

[ 0.          0.84210526  1.68421053  2.52631579  3.36842105  4.21052632
  5.05263158  5.89473684  6.73684211  7.57894737  8.42105263  9.26315789
 10.10526316 10.94736842 11.78947368 12.63157895 13.47368421 14.31578947
 15.15789474 16.        ]


In [43]:
arr = arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


In [45]:
arr = arange(1,12,2)
print(arr)

[ 1  3  5  7  9 11]


In [46]:
arr = logspace(1,40,5)
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [47]:
arr = logspace(1,2,5)
print(arr)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [51]:
arr = logspace(1,40,5)
print('%.2f' %arr[4])

10000000000000000303786028427003666890752.00


In [55]:
arr = zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [63]:
arr = ones(5,int)

print(arr)

[1 1 1 1 1]


In [64]:
arr = ones(5)
print(arr)

[1. 1. 1. 1. 1.]


copying an array in python

In [65]:
from numpy import *

In [66]:
arr = array([1,2,3,4,5])
arr = arr + 5
print(arr)

[ 6  7  8  9 10]


In [67]:
arr1 = array([1,2,3,4,5])
arr2 = array([6,7,8,9,0])
arr3 = arr1 + arr2
print(arr3)

[ 7  9 11 13  5]


In [68]:
arr = array([1,2,3,4,5])
print(sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [69]:
arr = array([1,2,3,4,5])
print(log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [70]:
arr = array([1,2,3,4,5])
print(cos(arr))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [71]:
arr = array([1,2,3,4,5])
print(sum(arr))

15


In [72]:
arr = array([1,2,3,4,5])
print(min(arr))

1


In [73]:
arr = array([1,2,3,4,5])
print(max(arr))

5


In [74]:
arr = array([1,2,3,4,5])
print(tan(arr))

[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [75]:
arr1 = array([1,2,3,4,5])
arr2 = array([6,7,8,9,0])
arr3 = arr1 + arr2 + 5
print(arr3)

[12 14 16 18 10]


In [76]:
arr1 = array([1,2,3,4,5])
arr2 = array([6,7,8,9,0])
arr3 = arr1 + 8
print(arr3)

[ 9 10 11 12 13]


In [78]:
arr1 = array([1,2,3,4,5])
arr2 = array([6,7,8,9,0])
print(concatenate([arr1,arr2]))

[1 2 3 4 5 6 7 8 9 0]


In [80]:
arr1 = array([1,2,3,4,5])
arr2 = arr1
print(arr1)
print(arr2)

[1 2 3 4 5]
[1 2 3 4 5]


In [82]:
arr1 = array([1,2,3,4,5])
arr2 = arr1
print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[1 2 3 4 5]
[1 2 3 4 5]
2508496153904
2508496153904


In [83]:
arr1 = array([1,2,3,4,5])
arr2 = arr1.view()


print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[1 2 3 4 5]
[1 2 3 4 5]
2508481687312
2508496929584


In [89]:
arr1 = array([1,2,3,4,5])
arr2 = arr1.view()

arr1[3] = 7
print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[1 2 3 7 5]
[1 2 3 7 5]
2508496153904
2508496933808


In [90]:
arr1 = array([1,2,3,4,5])
arr2 = arr1.copy()

arr1[3] = 7
print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[1 2 3 7 5]
[1 2 3 4 5]
2508481687312
2508496943600


working with matrix 

In [3]:
from numpy import * 
arr1 = array([
               [1,2,3],
               [4,5,6]
])
print(arr1.dtype)

int32


In [4]:
from numpy import * 
arr1 = array([
               [1,2,3],
               [4,5,6]
])
print(arr1.ndim)

2


In [5]:
from numpy import * 
arr1 = array([
               [1,2,3],
               [4,5,6]
])
print(arr1.shape)

(2, 3)


In [6]:
from numpy import * 
arr1 = array([
               [1,2,3],
               [4,5,6]
])
print(arr1.size)

6


In [7]:
from numpy import * 
arr1 = array([
               [1,2,3],
               [4,5,6]
])
arr2 = arr1.flatten()
print(arr2)

[1 2 3 4 5 6]


In [10]:
from numpy import * 
arr1 = array([
               [1,2,3,6,2,9],
               [4,5,6,7,5,3]
])
arr2 = arr1.flatten()
arr3 = arr2.reshape(3,4)
print(arr3)

[[1 2 3 6]
 [2 9 4 5]
 [6 7 5 3]]


In [11]:
from numpy import * 
arr1 = array([
               [1,2,3,6,2,9],
               [4,5,6,7,5,3]
])
arr2 = arr1.flatten()
arr3 = arr2.reshape(2,2,3)
print(arr3)

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [13]:
from numpy import * 
arr1 = array([
               [1,2,3,6],
               [4,5,6,7]
])
m = matrix(arr1)

print(m)

[[1 2 3 6]
 [4 5 6 7]]


In [22]:
from numpy import * 

m = matrix('1 2 3 6 ; 4 5 7 7')

print(m)

[[1 2 3 6]
 [4 5 7 7]]


In [23]:
from numpy import * 

m = matrix('1 2 ; 3 6 ; 4 5 ; 7 7')

print(m)

[[1 2]
 [3 6]
 [4 5]
 [7 7]]


In [24]:
from numpy import * 

m = matrix('1 2 3 ; 6  4 5 ;  7 7 9')

print(m)

[[1 2 3]
 [6 4 5]
 [7 7 9]]


In [25]:
from numpy import * 

m = matrix('1 2 3 ; 6  4 5 ;  7 7 9')

print(diagonal(m))

[1 4 9]


In [26]:
from numpy import * 

m = matrix('1 2 3 ; 6  4 5 ;  7 7 9')

print(m.min())

1


In [27]:
from numpy import * 

m = matrix('1 2 3 ; 6  4 5 ;  7 7 9')

print(m.max())

9


In [28]:
from numpy import * 

m1 = matrix('1 2 3 ; 6  4 5 ;  7 7 9')
m2 = matrix('1 2 3 ; 6  4 5 ;  7 7 9')

m3 = m1 + m2;

print(m3)


[[ 2  4  6]
 [12  8 10]
 [14 14 18]]


In [29]:
from numpy import * 

m1 = matrix('1 2 3 ; 6  4 5 ;  7 7 9')
m2 = matrix('1 2 3 ; 6  4 5 ;  7 7 9')

m3 = m1 * m2;

print(m3)


[[ 34  31  40]
 [ 65  63  83]
 [112 105 137]]
